[phases.setup]
nixPkgs = ["cmake", "gcc", "openblas"]

[phases.install]
cmds = [
  "python3 -m ensurepip --upgrade",
  "python3 -m pip install setuptools",
  "python3 -m pip install dlib==19.24.6",
  "python3 -m pip install -r requirements.txt"
]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"